apiVersion: v1
kind: Secret
metadata:
  name: {{ include "three-tier-chart.fullname" . }}-secret
  labels:
    {{- include "three-tier-chart.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_NAME: {{ .Values.secret.dbName | quote }}
  DB_USER: {{ .Values.secret.dbUser | quote }}
